#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : compat-re2-soname10
Version  : 2023.03.01
Release  : 49
URL      : https://github.com/google/re2/archive/2023-03-01/re2-2023.03.01.tar.gz
Source0  : https://github.com/google/re2/archive/2023-03-01/re2-2023.03.01.tar.gz
Summary  : RE2 is a fast, safe, thread-friendly regular expression engine.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause
Requires: compat-re2-soname10-lib = %{version}-%{release}
Requires: compat-re2-soname10-license = %{version}-%{release}
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is the source code repository for RE2, a regular expression library.
For documentation about how to install and use RE2,
visit https://github.com/google/re2/.

%package lib
Summary: lib components for the compat-re2-soname10 package.
Group: Libraries
Requires: compat-re2-soname10-license = %{version}-%{release}

%description lib
lib components for the compat-re2-soname10 package.


%package license
Summary: license components for the compat-re2-soname10 package.
Group: Default

%description license
license components for the compat-re2-soname10 package.


%prep
%setup -q -n re2-2023-03-01
cd %{_builddir}/re2-2023-03-01
pushd ..
cp -a re2-2023-03-01 buildavx2
popd
pushd ..
cp -a re2-2023-03-01 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693935040
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -Ofast -falign-functions=32 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
make  %{?_smp_mflags}  includedir=/usr/include libdir=/usr/lib64

pushd ../buildavx2
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}  includedir=/usr/include libdir=/usr/lib64
popd
pushd ../buildavx512
export CFLAGS="$CFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v4"
make  %{?_smp_mflags}  includedir=/usr/include libdir=/usr/lib64
popd

%install
export SOURCE_DATE_EPOCH=1693935040
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-re2-soname10
cp %{_builddir}/re2-2023-03-01/LICENSE %{buildroot}/usr/share/package-licenses/compat-re2-soname10/e310076ee4f65219003bfae2427646e0236c5141 || :
cp %{_builddir}/re2-2023-03-01/re2/fuzzing/compiler-rt/LICENSE %{buildroot}/usr/share/package-licenses/compat-re2-soname10/483d1c97dc79ef8741eae507897ca39cfe19da36 || :
pushd ../buildavx2/
%make_install_v3 includedir=/usr/include libdir=/usr/lib64
popd
pushd ../buildavx512/
%make_install_v4 includedir=/usr/include libdir=/usr/lib64
popd
%make_install includedir=/usr/include libdir=/usr/lib64
## Remove excluded files
rm -f %{buildroot}*/usr/include/re2/filtered_re2.h
rm -f %{buildroot}*/usr/include/re2/re2.h
rm -f %{buildroot}*/usr/include/re2/set.h
rm -f %{buildroot}*/usr/include/re2/stringpiece.h
rm -f %{buildroot}*/usr/lib64/libre2.so
rm -f %{buildroot}*/usr/lib64/pkgconfig/re2.pc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libre2.so.10.0.0
/V4/usr/lib64/libre2.so.10.0.0
/usr/lib64/libre2.so.10
/usr/lib64/libre2.so.10.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-re2-soname10/483d1c97dc79ef8741eae507897ca39cfe19da36
/usr/share/package-licenses/compat-re2-soname10/e310076ee4f65219003bfae2427646e0236c5141
